Document: skdownloader
Title: Debian skdownloader Manual
Author: <insert document author here>
Abstract: This manual describes what skdownloader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/skdownloader/skdownloader.sgml.gz

Format: postscript
Files: /usr/share/doc/skdownloader/skdownloader.ps.gz

Format: text
Files: /usr/share/doc/skdownloader/skdownloader.text.gz

Format: HTML
Index: /usr/share/doc/skdownloader/html/index.html
Files: /usr/share/doc/skdownloader/html/*.html
