#https://gitlab.com/gitlab-org/gitlab-ce/issues/27921
# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: resin/armv7hf-debian:stretch
#image: sdthirlwall/raspberry-pi-cross-compiler

# Define commands that run before each job's script
before_script:
  - echo "deb-src http://archive.raspbian.org/raspbian/ stretch main contrib non-free rpi" >> /etc/apt/sources.list
  - apt-get update
  - apt-get install -y apt-utils
  - apt-get install -y gcc g++ libcurl4-openssl-dev dh-make devscripts build-essential fakeroot libspdlog-dev python3
  - apt-get -y dist-upgrade

# Try to compile our sample hello world app
build:
  stage: build
  script:
  # Compile our app
  - make release
  - cd build/skdownloader-*
  - debuild -us -uc -d
  - cd ..
  - sudo dpkg -i skdownloader_*_all.deb
  artifacts:
    paths:
    - build/skdownloader_*_all.deb

